//Write an Apex script that queries all "Account" records with related "Opportunity" records, and groups the opportunities by "StageName" and
// calculates the count of opportunities for each stage. 
//The script should then update the "Account" record's custom fields for each stage, storing the corresponding count of opportunities.





public class A9q4 {
    public static void ismeth(){
        
    }

}